name: Valami név

on:
  push:
    branches: [ master ]
    paths:
      - '**.js'
  pull_request:
   branches:    
      - master
      - '!main'
    # tags:        
    #   - v1           
    #   - v1.*
  release:
    types: 
      - created
  page_build:
  schedule:
    - cron:  '* */2 * * *'
    #. * * * * * --> perc(0-59), óra(0-23), nap(1-31), hónap(1-12)(JAN-DEC), hét_napja(0-6)(SUN-SAT)
    #. * = mind; ,=és; -=tól-ig; */15 = minden 15. (perc)

env:
  SERVER: production

jobs:
  teszt:
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    - name: My first step
      uses: actions/hello_world@main
      with:
        first_name: Mona
        middle_name: The
        last_name: Octocat 

  build:
    name: Buiiild
    runs-on: self-hosted
    needs: teszt
    steps:
    - name: Frissítés
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci
      working-directory: ./
      shell: bash

    - name: Restart PM2 server
      run: pm2 restart index

